/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge05;

import java.util.Arrays;

public class App {


    public static void main(String[] args) {
            var   list = new LinkedList ();

      //add item to the list
        list.addToLast(10);
        list.addToLast(20);
        list.addToLast(30);
        // add item to the head
        list.addToFirst(40);
        list.addToFirst(50);
        list.addToFirst(60);
        // find idx of item
        System.out.println(list.includes(100));
//        System.out.println(list.indexOf(40));
        System.out.println(list.toString());


    }


}
